### ISSUE TITLE
windows 7, python 2.7.11 32bit - installation error

### ISSUE THREAD

**Issue by denfromufa** [xdress/xdress#285]
C:\>pip install xdress
Collecting xdress
  Using cached xdress-0.4.tar.gz
Building wheels for collected packages: xdress
  Running setup.py bdist_wheel for xdress ... error
  Complete output from command C:\Python\Python27_32b\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\denis~1.akh\\appdata\\local\\temp\\pip-build-vc9p5x\\xdress\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\denis~1.akh\appdata\local\temp\tmpxkf7w6pip-wheel- --python-tag cp27:

  XXXXXXX       XXXXXXXDDDDDDDDDDDDD
  X:::::X       X:::::XD::::::::::::DDD
  X:::::X       X:::::XD:::::::::::::::DD
  X::::::X     X::::::XDDD:::::DDDDD:::::D
  XXX:::::X   X:::::XXX  D:::::D    D:::::D
     X:::::X X:::::X     D:::::D     D:::::D
      X:::::X:::::X      D:::::D     D:::::D
       X:::::::::X       D:::::D     D:::::D
       X:::::::::X       D:::::D     D:::::D
      X:::::X:::::X      D:::::D     D:::::D
     X:::::X X:::::X     D:::::D     D:::::D
  XXX:::::X   X:::::XXX  D:::::D    D:::::D
  X::::::X     X::::::XDDD:::::DDDDD:::::D
  X:::::X       X:::::XD:::::::::::::::DD
  X:::::X       X:::::XD::::::::::::DDD
  XXXXXXX       XXXXXXXDDDDDDDDDDDDD

  Disabling clang since llvm-config not found: tried llvm-config, llvm-config-3.5, llvm-config-3.4, llvm-config-3.3, llvm-config-3.2
  To override, set the LLVM_CONFIG environment variable.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\xdress
  copying xdress\astparsers.py -> build\lib\xdress
  copying xdress\autoall.py -> build\lib\xdress
  copying xdress\autodescribe.py -> build\lib\xdress
  copying xdress\base.py -> build\lib\xdress
  copying xdress\cythongen.py -> build\lib\xdress
  copying xdress\descfilter.py -> build\lib\xdress
  copying xdress\doxygen.py -> build\lib\xdress
  copying xdress\dtypes.py -> build\lib\xdress
  copying xdress\extratypes.py -> build\lib\xdress
  copying xdress\main.py -> build\lib\xdress
  copying xdress\pep8names.py -> build\lib\xdress
  copying xdress\plugins.py -> build\lib\xdress
  copying xdress\stlwrap.py -> build\lib\xdress
  copying xdress\typesystem.py -> build\lib\xdress
  copying xdress\utils.py -> build\lib\xdress
  copying xdress\version.py -> build\lib\xdress
  copying xdress\__init__.py -> build\lib\xdress
  creating build\lib\xdress\clang
  copying xdress\clang\cindex.py -> build\lib\xdress\clang
  copying xdress\clang\enumerations.py -> build\lib\xdress\clang
  copying xdress\clang\__init__.py -> build\lib\xdress\clang
  creating build\lib\xdress\_enum
  copying xdress\_enum\enum.py -> build\lib\xdress\_enum
  copying xdress\_enum\test_enum.py -> build\lib\xdress\_enum
  copying xdress\_enum\__init__.py -> build\lib\xdress\_enum
  copying xdress\xdress_extra_types.pxd -> build\lib\xdress
  copying xdress\xdress_extra_types.pyx -> build\lib\xdress
  copying xdress\xdress_extra_types.h -> build\lib\xdress
  copying xdress\_enum\LICENSE -> build\lib\xdress\_enum
  copying xdress\_enum\README -> build\lib\xdress\_enum
  running build_scripts
  creating build\scripts-2.7
  copying and adjusting c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\scripts\xdress -> build\scripts-2.7
  copying c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\scripts\xdress.bat -> build\scripts-2.7
  installing to build\bdist.win32\wheel
  running install
  running install_lib
  creating build\bdist.win32
  creating build\bdist.win32\wheel
  creating build\bdist.win32\wheel\xdress
  copying build\lib\xdress\astparsers.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\autoall.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\autodescribe.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\base.py -> build\bdist.win32\wheel\.\xdress
  creating build\bdist.win32\wheel\xdress\clang
  copying build\lib\xdress\clang\cindex.py -> build\bdist.win32\wheel\.\xdress\clang
  copying build\lib\xdress\clang\enumerations.py -> build\bdist.win32\wheel\.\xdress\clang
  copying build\lib\xdress\clang\__init__.py -> build\bdist.win32\wheel\.\xdress\clang
  copying build\lib\xdress\cythongen.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\descfilter.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\doxygen.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\dtypes.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\extratypes.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\main.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\pep8names.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\plugins.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\stlwrap.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\typesystem.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\utils.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\version.py -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\xdress_extra_types.h -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\xdress_extra_types.pxd -> build\bdist.win32\wheel\.\xdress
  copying build\lib\xdress\xdress_extra_types.pyx -> build\bdist.win32\wheel\.\xdress
  creating build\bdist.win32\wheel\xdress\_enum
  copying build\lib\xdress\_enum\enum.py -> build\bdist.win32\wheel\.\xdress\_enum
  copying build\lib\xdress\_enum\LICENSE -> build\bdist.win32\wheel\.\xdress\_enum
  copying build\lib\xdress\_enum\README -> build\bdist.win32\wheel\.\xdress\_enum
  copying build\lib\xdress\_enum\test_enum.py -> build\bdist.win32\wheel\.\xdress\_enum
  copying build\lib\xdress\_enum\__init__.py -> build\bdist.win32\wheel\.\xdress\_enum
  copying build\lib\xdress\__init__.py -> build\bdist.win32\wheel\.\xdress
  running install_data
  creating build\bdist.win32\wheel\xdress-0.4.data
  creating build\bdist.win32\wheel\xdress-0.4.data\data
  copying license -> build\bdist.win32\wheel\xdress-0.4.data\data\
  copying configure.py -> build\bdist.win32\wheel\xdress-0.4.data\data\
  running install_egg_info
  running egg_info
  writing xdress.egg-info\PKG-INFO
  writing top-level names to xdress.egg-info\top_level.txt
  writing dependency_links to xdress.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'xdress.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\setup.py", line 32, in <module>
      main()
    File "c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\setup.py", line 29, in main
      configure.setup()
    File "c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\configure.py", line 186, in setup
      setup_(**setup_kwargs)
    File "C:\Python\Python27_32b\lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "C:\Python\Python27_32b\lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "C:\Python\Python27_32b\lib\site-packages\wheel\bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "C:\Python\Python27_32b\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "build\bdist.win32\egg\setuptools\command\install.py", line 61, in run
    File "C:\Python\Python27_32b\lib\distutils\command\install.py", line 575, in run
      self.run_command(cmd_name)
    File "C:\Python\Python27_32b\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "build\bdist.win32\egg\setuptools\command\install_egg_info.py", line 35, in run
    File "C:\Python\Python27_32b\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 193, in run
    File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 216, in find_sources
    File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 300, in run
    File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 336, in add_defaults
    File "build\bdist.win32\egg\setuptools\command\sdist.py", line 195, in read_manifest
    File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 241, in append
    File "C:\Python\Python27_32b\lib\distutils\util.py", line 124, in convert_path
      raise ValueError, "path '%s' cannot be absolute" % pathname
  ValueError: path '/home/scopatz/xdress/scripts/xdress' cannot be absolute

  ----------------------------------------
  Failed building wheel for xdress
  Running setup.py clean for xdress
Failed to build xdress
Installing collected packages: xdress
  Running setup.py install for xdress ... error
    Complete output from command C:\Python\Python27_32b\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\denis~1.akh\\appdata\\local\\temp\\pip-build-vc9p5x\\xdress\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\denis~1.akh\appdata\local\temp\pip-evz9xy-record\install-record.txt --single-version-externally-managed --compile:

    XXXXXXX       XXXXXXXDDDDDDDDDDDDD
    X:::::X       X:::::XD::::::::::::DDD
    X:::::X       X:::::XD:::::::::::::::DD
    X::::::X     X::::::XDDD:::::DDDDD:::::D
    XXX:::::X   X:::::XXX  D:::::D    D:::::D
       X:::::X X:::::X     D:::::D     D:::::D
        X:::::X:::::X      D:::::D     D:::::D
         X:::::::::X       D:::::D     D:::::D
         X:::::::::X       D:::::D     D:::::D
        X:::::X:::::X      D:::::D     D:::::D
       X:::::X X:::::X     D:::::D     D:::::D
    XXX:::::X   X:::::XXX  D:::::D    D:::::D
    X::::::X     X::::::XDDD:::::DDDDD:::::D
    X:::::X       X:::::XD:::::::::::::::DD
    X:::::X       X:::::XD::::::::::::DDD
    XXXXXXX       XXXXXXXDDDDDDDDDDDDD

    Disabling clang since llvm-config not found: tried llvm-config, llvm-config-3.5, llvm-config-3.4, llvm-config-3.3, llvm-config-3.2
    To override, set the LLVM_CONFIG environment variable.
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\xdress
    copying xdress\astparsers.py -> build\lib\xdress
    copying xdress\autoall.py -> build\lib\xdress
    copying xdress\autodescribe.py -> build\lib\xdress
    copying xdress\base.py -> build\lib\xdress
    copying xdress\cythongen.py -> build\lib\xdress
    copying xdress\descfilter.py -> build\lib\xdress
    copying xdress\doxygen.py -> build\lib\xdress
    copying xdress\dtypes.py -> build\lib\xdress
    copying xdress\extratypes.py -> build\lib\xdress
    copying xdress\main.py -> build\lib\xdress
    copying xdress\pep8names.py -> build\lib\xdress
    copying xdress\plugins.py -> build\lib\xdress
    copying xdress\stlwrap.py -> build\lib\xdress
    copying xdress\typesystem.py -> build\lib\xdress
    copying xdress\utils.py -> build\lib\xdress
    copying xdress\version.py -> build\lib\xdress
    copying xdress\__init__.py -> build\lib\xdress
    creating build\lib\xdress\clang
    copying xdress\clang\cindex.py -> build\lib\xdress\clang
    copying xdress\clang\enumerations.py -> build\lib\xdress\clang
    copying xdress\clang\__init__.py -> build\lib\xdress\clang
    creating build\lib\xdress\_enum
    copying xdress\_enum\enum.py -> build\lib\xdress\_enum
    copying xdress\_enum\test_enum.py -> build\lib\xdress\_enum
    copying xdress\_enum\__init__.py -> build\lib\xdress\_enum
    copying xdress\xdress_extra_types.pxd -> build\lib\xdress
    copying xdress\xdress_extra_types.pyx -> build\lib\xdress
    copying xdress\xdress_extra_types.h -> build\lib\xdress
    copying xdress\_enum\LICENSE -> build\lib\xdress\_enum
    copying xdress\_enum\README -> build\lib\xdress\_enum
    running build_scripts
    creating build\scripts-2.7
    copying and adjusting c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\scripts\xdress -> build\scripts-2.7
    copying c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\scripts\xdress.bat -> build\scripts-2.7
    running install_lib
    running install_data
    running install_egg_info
    running egg_info
    writing xdress.egg-info\PKG-INFO
    writing top-level names to xdress.egg-info\top_level.txt
    writing dependency_links to xdress.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'xdress.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\setup.py", line 32, in <module>
        main()
      File "c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\setup.py", line 29, in main
        configure.setup()
      File "c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\configure.py", line 186, in setup
        setup_(**setup_kwargs)
      File "C:\Python\Python27_32b\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python\Python27_32b\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\install.py", line 61, in run
      File "C:\Python\Python27_32b\lib\distutils\command\install.py", line 575, in run
        self.run_command(cmd_name)
      File "C:\Python\Python27_32b\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\install_egg_info.py", line 35, in run
      File "C:\Python\Python27_32b\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python\Python27_32b\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 193, in run
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 216, in find_sources
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 300, in run
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 336, in add_defaults
      File "build\bdist.win32\egg\setuptools\command\sdist.py", line 195, in read_manifest
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 241, in append
      File "C:\Python\Python27_32b\lib\distutils\util.py", line 124, in convert_path
        raise ValueError, "path '%s' cannot be absolute" % pathname
    ValueError: path '/home/scopatz/xdress/scripts/xdress' cannot be absolute

    ----------------------------------------
Command "C:\Python\Python27_32b\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\denis~1.akh\\appdata\\local\\temp\\pip-build-vc9p5x\\xdress\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\denis~1.akh\appdata\local\temp\pip-evz9xy-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\denis~1.akh\appdata\local\temp\pip-build-vc9p5x\xdress\
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by scopatz** [comment]
Sorry you are having problems. If you come up with a fix, I would be happy to merge it.

**Comment by denfromufa** [comment]
actually it works from the master:

```
C:\>pip install git+https://github.com/xdress/xdress -U
Collecting git+https://github.com/xdress/xdress
  Cloning https://github.com/xdress/xdress to
c:\users\denis~1.akh\appdata\local
\temp\pip-nopojx-build
Installing collected packages: xdress
  Found existing installation: xdress 0.5.dev0
    Uninstalling xdress-0.5.dev0:
      Successfully uninstalled xdress-0.5.dev0
  Running setup.py install for xdress ... done
Successfully installed xdress-0.5.dev0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.
```

**Comment by scopatz** [comment]
Ok great!
