### ISSUE TITLE
On install: `AttributeError: module 'distutils.spawn' has no attribute '_spawn_posix'`

### ISSUE THREAD

**Issue by jakirkham** [xdress/xdress#292]
Seeing the following issue when trying to install via `pip`

```python
$ python -m pip install xdress
Collecting xdress
  Using cached xdress-0.4.tar.gz (163 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lw/whnppx9951323x027sfhl5mmglk2pt/T/pip-install-fshu27xl/xdress_cfd17108ed834f0da320bfc289cfb95c/setup.py", line 4, in <module>
          import configure
        File "/private/var/folders/lw/whnppx9951323x027sfhl5mmglk2pt/T/pip-install-fshu27xl/xdress_cfd17108ed834f0da320bfc289cfb95c/configure.py", line 19, in <module>
          old_spawn_posix = distutils.spawn._spawn_posix
      AttributeError: module 'distutils.spawn' has no attribute '_spawn_posix'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jakirkham** [comment]
Seems to be related to this code:

https://github.com/xdress/xdress/blob/eb7f0a02b3edf617d401939ede7f0d713a88917f/configure.py#L19-L22

Simply skipping if `_spawn_posix` does not exist seems to work
